# .github/workflows/fly-deploy.yml
# This workflow deploys your application to Fly.io using GitHub Actions.
# For more information, see: https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  push:
    branches:
      - main # This workflow runs on pushes to the 'main' branch

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} # Ensures only one deploy per branch
      cancel-in-progress: true # Cancels previous running workflow if a new push occurs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest stable version of checkout action

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@1.3 # Use a specific release tag for stability
        # You can find the latest stable tag here: https://github.com/superfly/flyctl-actions/releases

      - name: Deploy app
        run: flyctl deploy --remote-only # --remote-only ensures build happens on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} # Ensure this secret is configured in GitHub